//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int IdEvent { get; set; }
        public string nomEvent { get; set; }
        public string Date { get; set; }
        public string lieu { get; set; }
        public string Type { get; set; }
        public string cible { get; set; }
    }
}
