//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organisateur
    {
        public int IdOrganisateur { get; set; }
        public string nomOrganisateur { get; set; }
        public int numTel { get; set; }
        public string mail { get; set; }
        public string adresse { get; set; }
    }
}
