//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public int IdSession { get; set; }
        public int IdSpeaker { get; set; }
        public string sujet { get; set; }
        public string horaire { get; set; }
        public int IdEvent { get; set; }
    }
}
