//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Speaker
    {
        public int IdSpeaker { get; set; }
        public string nomSpeaker { get; set; }
        public int numTel { get; set; }
        public string adresse { get; set; }
        public string mail { get; set; }
    }
}
